# Generated by Django 5.1.3 on 2024-11-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="branch",
            field=models.CharField(max_length=50),
        ),
    ]
